/**
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.10
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import EvaluationEntity from './EvaluationEntity';





/**
* The EvaluationBatchRequest model module.
* @module model/EvaluationBatchRequest
* @version 1.0.10
*/
export default class EvaluationBatchRequest {
    /**
    * Constructs a new <code>EvaluationBatchRequest</code>.
    * @alias module:model/EvaluationBatchRequest
    * @class
    * @param entities {Array.<module:model/EvaluationEntity>} 
    */

    constructor(entities) {
        

        
        

        this['entities'] = entities;

        
    }

    /**
    * Constructs a <code>EvaluationBatchRequest</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EvaluationBatchRequest} obj Optional instance to populate.
    * @return {module:model/EvaluationBatchRequest} The populated <code>EvaluationBatchRequest</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EvaluationBatchRequest();

            
            
            

            if (data.hasOwnProperty('entities')) {
                obj['entities'] = ApiClient.convertToType(data['entities'], [EvaluationEntity]);
            }
            if (data.hasOwnProperty('enableDebug')) {
                obj['enableDebug'] = ApiClient.convertToType(data['enableDebug'], 'Boolean');
            }
            if (data.hasOwnProperty('flagIDs')) {
                obj['flagIDs'] = ApiClient.convertToType(data['flagIDs'], ['Number']);
            }
            if (data.hasOwnProperty('flagKeys')) {
                obj['flagKeys'] = ApiClient.convertToType(data['flagKeys'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/EvaluationEntity>} entities
    */
    entities = undefined;
    /**
    * @member {Boolean} enableDebug
    */
    enableDebug = undefined;
    /**
    * flagIDs
    * @member {Array.<Number>} flagIDs
    */
    flagIDs = undefined;
    /**
    * flagKeys. Either flagIDs or flagKeys works. If pass in both, Flagr may return duplicate results.
    * @member {Array.<String>} flagKeys
    */
    flagKeys = undefined;








}


